import JSZip from 'jszip';
export async function demoBook() {
  const zip = new JSZip();
  zip.file('mimetype', 'application/epub+zip', { compression: 'STORE' });
  zip.file('META-INF/container.xml', '<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>');
  zip.file('OEBPS/content.opf', '<?xml version="1.0"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="id">epubaudio-demo-1</dc:identifier><dc:title>Những khoảng lặng</dc:title><dc:creator>EpubAudio</dc:creator><dc:language>vi</dc:language><meta property="dcterms:modified">2026-10-04T00:00:00Z</meta></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/><item id="c1" href="chapter1.xhtml" media-type="application/xhtml+xml"/><item id="c2" href="chapter2.xhtml" media-type="application/xhtml+xml"/><item id="css" href="style.css" media-type="text/css"/></manifest><spine><itemref idref="c1"/><itemref idref="c2"/></spine></package>');
  zip.file('OEBPS/nav.xhtml', '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>Mục lục</title></head><body><nav epub:type="toc"><ol><li><a href="chapter1.xhtml">01. Một buổi sáng chậm</a></li><li><a href="chapter2.xhtml">02. Lắng nghe trang sách</a></li></ol></nav></body></html>');
  zip.file('OEBPS/style.css', 'body{font-family:Georgia,serif;line-height:1.9;color:#353a33;padding:16px 24px}h1{font-weight:400;font-size:2.2em;line-height:1.35;margin:1em 0}p{margin:1em 0}blockquote{border-left:2px solid #9fae90;padding-left:1em;font-style:italic}small{letter-spacing:.18em;color:#78806e}');
  const chapter = (title, body) => `<html xmlns="http://www.w3.org/1999/xhtml"><head><title>${title}</title><link href="style.css" rel="stylesheet" type="text/css"/></head><body>${body}</body></html>`;
  zip.file('OEBPS/chapter1.xhtml', chapter('Một buổi sáng chậm', '<small>CHƯƠNG MỘT</small><h1>Một buổi sáng chậm</h1><p>Buổi sáng ấy, tôi mở cửa sổ sớm hơn thường lệ. Một vệt nắng mỏng nằm trên bàn, cạnh cuốn sách còn mở từ tối qua. Ngoài kia, thành phố đang thức dậy. Nhưng trong căn phòng nhỏ, mọi thứ vẫn chậm rãi.</p><p>Tôi pha một tách trà, đặt điện thoại xuống, rồi ngồi vào chiếc ghế quen thuộc. Không có điều gì cần phải vội. Một trang sách, một hơi thở, một ngụm trà — đôi khi, như vậy đã đủ cho một khởi đầu.</p><blockquote>“Có những điều chỉ nghe thấy khi chúng ta dành cho mình một khoảng lặng.”</blockquote><p>Đọc sách là một cách ở lại với khoảnh khắc. Ta không cần đi thật nhanh để đến cuối một câu chuyện. Ta có thể dừng trước một câu đẹp, đọc lại một đoạn văn, hoặc khép mắt và để những lời ấy tự tìm đến mình.</p><p>Khi nghe một giọng đọc, tôi nhận ra dấu phẩy cũng có âm thanh của nó. Dấu chấm là một khoảng nghỉ. Một đoạn văn mới giống như bước chân vừa rẽ sang một con đường khác.</p><p>Trang sách vẫn là trang sách ấy. Chỉ có cách ta gặp nó là đổi khác: có lúc bằng đôi mắt, có lúc bằng đôi tai, và có lúc bằng cả hai.</p><p>Ánh nắng dịch thêm một chút. Tách trà đã bớt nóng. Tôi lật sang trang tiếp theo, lòng nhẹ như một chiếc lá vừa chạm xuống mặt nước.</p>'));
  zip.file('OEBPS/chapter2.xhtml', chapter('Lắng nghe trang sách', '<small>CHƯƠNG HAI</small><h1>Lắng nghe trang sách</h1><p>Mỗi cuốn sách có nhịp riêng. Một câu ngắn kéo ta lại gần. Một câu dài đưa ta đi qua những ngõ nhỏ của ký ức. Khi lắng nghe, nhịp ấy trở nên rõ ràng hơn.</p><p>Bạn có thể mang câu chuyện theo mình khi ngồi bên cửa sổ, khi nghỉ ngơi, hay trong một buổi chiều yên tĩnh. Những từ đang vang lên được đánh dấu nhẹ trên trang, để đôi mắt luôn tìm lại được đường về.</p><p>Đây là sách mẫu do EpubAudio viết để bạn thử giao diện. Hãy thêm một cuốn EPUB của riêng bạn để bắt đầu thư viện của mình.</p>'));
  return new File([await zip.generateAsync({ type: 'arraybuffer' })], 'Những khoảng lặng.epub', { type: 'application/epub+zip' });
}
